name: Run Tests for find_lowest_number

on:
  push:
    branches:
      - main

jobs:
  automated-testing:
    runs-on: ubuntu-latest

    steps:
    - name: Clone Repository
      uses: actions/checkout@v3

    - name: Configure Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Execute Test Case 1 - Multiple Entries
      run: |
        python3 find_lowest_number.py test_data/test1_input.txt test_data/test1_output.txt
        diff test_data/test1_output.txt test_data/test1_expected.txt

    - name: Execute Test Case 2 - Single Number
      run: |
        python3 find_lowest_number.py test_data/test2_input.txt test_data/test2_output.txt
        diff test_data/test2_output.txt test_data/test2_expected.txt

    - name: Execute Test Case 3 - Empty File
      run: |
        python3 find_lowest_number.py test_data/test3_input.txt test_data/test3_output.txt
        diff test_data/test3_output.txt test_data/test3_expected.txt


      - name: Run test case 2
        run: |
          python3 find_lowest_number.py test_data/test2_input.txt test_data/test2_output.txt
          diff test_data/test2_output.txt test_data/test2_expected.txt

      - name: Run test case 3
        run: |
          python3 find_lowest_number.py test_data/test3_input.txt test_data/test3_output.txt
          diff test_data/test3_output.txt test_data/test3_expected.txt
